### ISSUE TITLE
Point Cloud Data Structure

### ISSUE THREAD

**Issue by super-zyw** [hyan46/TensorRegression#1]
Hi Dr.Yan, 
This work is pretty interesting. I have a problem when I try to run the algorithm using my point cloud data. 

The point cloud data is represented by x, y, z coordinates. The example waveform in the code tensor is 100 * 50 * 100 that is 100 * 50 size image for 100 samples, however, I cannot represent a real point cloud model by only a 2d image since for the same x, y location there might be several different z values. How did you deal with real point cloud data in the real case study?

**Comment by hyan46** [comment]
Thanks for the comments. This paper is designed for a structured point cloud, so it worked well if the point cloud lies in a regular grid structure on the 2D surface in 3D space so it can be represented by a 2D image. 

Technically the method can be extended into 3D but the representation of the unstructured point cloud from the 2D surface into 3D may be inefficient given that only the surface would have information. 

It also depends on what data you have, structured or unstructured. If it is unstructured, you may have to convert it to structured data with grid representation to use this method. If the measurement is already structured, the only problem is how to choose the coordinate system, such as cartesian,  spherical, cylindrical coordinate systems.
